### ISSUE TITLE
Support blog posts

### ISSUE THREAD

**Issue by RosieCampbell** [b3u/eleventy-garden#10]
Currently the template only supports notes - I'd like it to also support blog posts so I can use it to create a complete personal website.

**Comment by RosieCampbell** [comment]
Just submitted a pull request with this functionality

**Comment by b3u** [comment]
I like the idea of blog posts. I also want to keep the template simple, for people who only want the notes functionality. As a compromise, I could just write up a guide for adding a blog. Thoughts?

**Comment by RosieCampbell** [comment]
Yeah I definitely understand the desire to keep it simple. Adding a guide sounds good. We could also potentially have a separate repo that builds on this one that includes blog functionality and other stuff for people who want a full site.

**Comment by b3u** [comment]
closed via #13

**Comment by djdrysdale** [comment]
@RosieCampbell I'd be interested in incorporating a blog with my notes—did you manage it?
